name: Generate Image from Commit

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get commit message
        run: |
          echo "MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Generate image via DynaPictures
        run: |
          mkdir -p images

          RESPONSE=$(curl -X POST https://api.dynapictures.com/designs/${{ secrets.DYNAPICTURES_TEMPLATE_ID }} \
            -H "Authorization: Bearer ${{ secrets.DYNAPICTURES_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
                "format": "jpeg",
                "metadata": "some text",
                "params": [
                  {
                    "name": "text1",
                    "text": "Message de commit :"
                  },
                  {
                    "name": "text2",
                    "text": "'"${{ env.MESSAGE }}"'"
                  }
                ]
              }'
            )

          echo "Réponse API :"
          echo "$RESPONSE"

          IMAGE_URL=$(echo "$RESPONSE" | jq -r '.imageUrl')
          echo "IMAGE_URL=$IMAGE_URL"

          if [ "$IMAGE_URL" = "null" ] || [ -z "$IMAGE_URL" ]; then
            echo "Erreur : aucune image_url retournée par l'API"
            exit 1
          fi

          FILE_NAME="image-$(date +%s).png"
          curl -o images/$FILE_NAME $IMAGE_URL

          echo "IMAGE_NAME=$FILE_NAME" >> $GITHUB_ENV

      - name: Upload generated image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-generee
          path: images/${{ env.IMAGE_NAME }}

      - name: Generate index.html
        run: |
          echo "<html><body><h1>Generated Images test</h1>" > index.html
          for img in images/*
          do
            echo "<div><img src='$img' width='300'><p>$img</p></div>" >> index.html
          done
          echo "</body></html>" >> index.html

      - name: Debug images
        run: |
          echo "Liste des fichiers :"
          ls -l
          echo "Contenu images :"
          ls -l images || echo "Le dossier images n'existe pas"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .